# Generated by Django 4.2.6 on 2023-10-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartitem_delete_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
